[package]
name = "summer-boot"
version = "0.1.0"
rust-version = "1.60.0"
edition = "2021"
description = "summer boot web2"
authors = [
    "James Zow <Jameszow@163.com>"
]
license = "Apache-2.0"

[features]
default = ["macros"]

macros = [
    "summer-boot-codegen"
]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"]}
socket2 = "0.4.4"
summer-boot-codegen = { version = "0.1.0", path = "../summer-boot-codegen", optional = true }