name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v3
        with:
          rust-version: stable

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and fmt and test 
        run: |
          cargo build --verbose --target x86_64-unknown-linux-gnu
          cargo fmt --verbose --target x86_64-unknown-linux-gnu
          cargo test --verbose --target x86_64-unknown-linux-gnu

      - name: Build for Unix
        if: runner.os == 'Linux'
        run: |
          cargo build --verbose --target x86_64-unknown-linux-gnu
          cargo test --verbose --target x86_64-unknown-linux-gnu
