name: Rust CI

on:
  push:
    branches:
      - main  # 替换为您的主分支名称
  pull_request:
    branches:
      - main  # 替换为您的主分支名称

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}

    - name: Check with Cargo
      run: cargo check --verbose

    - name: Test with Cargo
      run: cargo test --verbose
